title: Jordan's website
description: Check out my projects!
logo: https://apps.fs.usda.gov/forest-atlas/assets/lives/forest-birds/Habitat-Water_Wood-duck_Aix-sponsa_Web-Birds0202.jpg
remote_theme: pages-themes/minimal@v0.2.0
